query appleValidate($receipt: String){
    appleValidate(receipt: $receipt){
        code
        message
        data{
            isValidated
            isCanceled
            isExpired
        }
    }
}